// VerkRadar MVP mock opportunity data.
// Later, replace this with Supabase data from the opportunities table.

window.VERKRADAR_OPPORTUNITIES = [
  {
    id: "opp-001",
    title: "Electrical maintenance for municipal buildings",
    buyer: "Reykjavík City",
    source: "Reykjavík Tenders",
    category: "Electrical",
    type: "tender",
    description:
      "Ongoing electrical maintenance for municipal buildings, including schools and community centres. Contractor must handle urgent repairs and planned maintenance.",
    deadline: daysFromNow(18),
    publishedDate: daysFromNow(-3),
    location: "Reykjavík",
    estimatedValue: 15000000,
    url: "https://example.com/rvk-el-001",
    cpvCode: "50711000",
    requirements: [
      "Licensed electrician",
      "Emergency response capability",
      "Previous building maintenance experience"
    ],
    keywords: ["electrical", "maintenance", "schools", "public buildings", "emergency response"],
    difficulty: "medium",
    status: "open"
  },
  {
    id: "opp-002",
    title: "Fire alarm inspection and service contract",
    buyer: "Suðurnes Municipality",
    source: "Municipal websites",
    category: "Electrical / Safety",
    type: "contract",
    description:
      "Inspection and maintenance of fire alarm systems across public buildings. Certification may be required.",
    deadline: daysFromNow(25),
    publishedDate: daysFromNow(-2),
    location: "Suðurnes",
    estimatedValue: 5000000,
    url: "https://example.com/sud-fire-002",
    cpvCode: "50413200",
    requirements: ["Fire alarm certification", "Service documentation", "Insurance"],
    keywords: ["fire alarm", "inspection", "certification", "public buildings", "safety"],
    difficulty: "medium",
    status: "open"
  },
  {
    id: "opp-003",
    title: "Office cleaning services for school buildings",
    buyer: "Kópavogur Municipality",
    source: "Municipal websites",
    category: "Cleaning",
    type: "tender",
    description:
      "Daily cleaning services for several school and office buildings, including waste disposal and sanitation.",
    deadline: daysFromNow(12),
    publishedDate: daysFromNow(-1),
    location: "Capital Area",
    estimatedValue: 9000000,
    url: "https://example.com/kop-clean-003",
    cpvCode: "90919300",
    requirements: ["Proof of insurance", "Staffing plan", "Quality control plan"],
    keywords: ["cleaning", "schools", "daily service", "sanitation", "office cleaning"],
    difficulty: "low",
    status: "open"
  },
  {
    id: "opp-004",
    title: "Website redesign for public institution",
    buyer: "Icelandic Public Institution",
    source: "Útboðsvefur",
    category: "IT / Web / Software",
    type: "tender",
    description:
      "Redesign and development of a public institution website. Includes accessibility, multilingual support, content migration and CMS setup.",
    deadline: daysFromNow(32),
    publishedDate: daysFromNow(-5),
    location: "Remote / Online",
    estimatedValue: 12000000,
    url: "https://example.com/gov-web-004",
    cpvCode: "72413000",
    requirements: ["Accessibility compliance", "CMS experience", "Multilingual support", "Content migration"],
    keywords: ["website", "web design", "accessibility", "multilingual", "CMS", "content migration"],
    difficulty: "high",
    status: "open"
  },
  {
    id: "opp-005",
    title: "EV charging station installation",
    buyer: "South Iceland Municipality",
    source: "Municipal websites",
    category: "Electrical / Infrastructure",
    type: "municipal-project",
    description:
      "Installation of EV charging stations in municipal parking areas and public facilities. Includes electrical installation and testing.",
    deadline: daysFromNow(38),
    publishedDate: daysFromNow(-7),
    location: "South Iceland",
    estimatedValue: 8000000,
    url: "https://example.com/south-ev-005",
    cpvCode: "45310000",
    requirements: ["Electrical installation license", "Testing documentation", "Project plan"],
    keywords: ["EV charging", "electrical installation", "public parking", "infrastructure"],
    difficulty: "medium",
    status: "open"
  },
  {
    id: "opp-006",
    title: "Landscaping maintenance for public parks",
    buyer: "Akureyri Municipality",
    source: "Municipal websites",
    category: "Landscaping",
    type: "contract",
    description: "Seasonal landscaping, mowing, planting, and maintenance services for public parks.",
    deadline: daysFromNow(20),
    publishedDate: daysFromNow(-2),
    location: "North Iceland",
    estimatedValue: 6500000,
    url: "https://example.com/ak-land-006",
    cpvCode: "77310000",
    requirements: ["Equipment list", "Seasonal staffing plan", "Safety plan"],
    keywords: ["landscaping", "parks", "mowing", "planting", "maintenance"],
    difficulty: "low",
    status: "open"
  },
  {
    id: "opp-007",
    title: "Security camera installation for school facilities",
    buyer: "Public School Network",
    source: "Útboðsvefur",
    category: "Security",
    type: "tender",
    description: "Installation of security cameras and access control in school facilities in the capital area.",
    deadline: daysFromNow(15),
    publishedDate: daysFromNow(-6),
    location: "Capital Area",
    estimatedValue: 7000000,
    url: "https://example.com/school-sec-007",
    cpvCode: "35120000",
    requirements: ["Security equipment experience", "Data protection process", "Installation plan"],
    keywords: ["security cameras", "access control", "schools", "installation", "electrical"],
    difficulty: "medium",
    status: "open"
  },
  {
    id: "opp-008",
    title: "Consulting project for digital transformation",
    buyer: "Government Agency",
    source: "EU TED",
    category: "Consulting / IT",
    type: "tender",
    description: "Consulting support for digital transformation, process mapping, implementation planning and training.",
    deadline: daysFromNow(45),
    publishedDate: daysFromNow(-8),
    location: "Reykjavík",
    estimatedValue: 18000000,
    url: "https://example.com/ted-digi-008",
    cpvCode: "72224000",
    requirements: ["Consulting references", "Project methodology", "Public sector experience"],
    keywords: ["consulting", "digital transformation", "process mapping", "training", "IT"],
    difficulty: "high",
    status: "open"
  },
  {
    id: "opp-009",
    title: "Transport service framework agreement",
    buyer: "Public Healthcare Provider",
    source: "Útboðsvefur",
    category: "Transport",
    type: "contract",
    description: "Framework agreement for regular transport services between healthcare facilities across Iceland.",
    deadline: daysFromNow(28),
    publishedDate: daysFromNow(-4),
    location: "All Iceland",
    estimatedValue: 25000000,
    url: "https://example.com/health-tran-009",
    cpvCode: "60100000",
    requirements: ["Vehicle documentation", "Insurance", "Service availability"],
    keywords: ["transport", "healthcare", "framework agreement", "vehicles", "logistics"],
    difficulty: "high",
    status: "open"
  },
  {
    id: "opp-010",
    title: "Building renovation contractor needed",
    buyer: "Housing Association",
    source: "Private lead",
    category: "Construction",
    type: "private-lead",
    description: "Renovation of common areas, exterior repairs and selected interior improvements.",
    deadline: daysFromNow(22),
    publishedDate: daysFromNow(-3),
    location: "Reykjavík",
    estimatedValue: 22000000,
    url: "https://example.com/reno-010",
    cpvCode: "",
    requirements: ["Renovation experience", "Insurance", "Timeline proposal"],
    keywords: ["construction", "renovation", "building", "exterior repairs", "interior improvements"],
    difficulty: "medium",
    status: "open"
  },
  {
    id: "opp-011",
    title: "Snow removal for municipal roads",
    buyer: "West Iceland Municipality",
    source: "Municipal websites",
    category: "Transport / Roadwork",
    type: "contract",
    description: "Snow removal, salting and emergency road clearing during winter season.",
    deadline: daysFromNow(16),
    publishedDate: daysFromNow(-9),
    location: "West Iceland",
    estimatedValue: 11000000,
    url: "https://example.com/snow-011",
    cpvCode: "90620000",
    requirements: ["Snow removal equipment", "24/7 response", "Winter service plan"],
    keywords: ["snow removal", "roadwork", "salting", "winter service"],
    difficulty: "medium",
    status: "open"
  },
  {
    id: "opp-012",
    title: "Mechanical workshop services for public fleet",
    buyer: "Public Transport Authority",
    source: "Útboðsvefur",
    category: "Equipment / Machinery",
    type: "contract",
    description: "Maintenance and repair services for a fleet of municipal vehicles and small machinery.",
    deadline: daysFromNow(31),
    publishedDate: daysFromNow(-4),
    location: "Capital Area",
    estimatedValue: 14000000,
    url: "https://example.com/fleet-012",
    cpvCode: "50100000",
    requirements: ["Workshop facilities", "Vehicle repair experience", "Parts availability"],
    keywords: ["mechanical", "workshop", "fleet", "repair", "machinery"],
    difficulty: "medium",
    status: "open"
  },
  {
    id: "opp-013",
    title: "Architecture design for community centre",
    buyer: "East Iceland Municipality",
    source: "Municipal websites",
    category: "Architecture / Engineering",
    type: "tender",
    description: "Architectural concept, planning, drawings and coordination for a new community centre.",
    deadline: daysFromNow(40),
    publishedDate: daysFromNow(-10),
    location: "East Iceland",
    estimatedValue: 16000000,
    url: "https://example.com/arch-013",
    cpvCode: "71200000",
    requirements: ["Architecture license", "Public building references", "Design timeline"],
    keywords: ["architecture", "design", "community centre", "planning", "drawings"],
    difficulty: "high",
    status: "open"
  },
  {
    id: "opp-014",
    title: "Cybersecurity review for small public agency",
    buyer: "Public Agency",
    source: "EU TED",
    category: "IT / Web / Software",
    type: "tender",
    description: "Security review of internal systems, vulnerability assessment and recommendations report.",
    deadline: daysFromNow(14),
    publishedDate: daysFromNow(-2),
    location: "Remote / Online",
    estimatedValue: 6500000,
    url: "https://example.com/cyber-014",
    cpvCode: "72810000",
    requirements: ["Security references", "Confidentiality agreement", "Technical report"],
    keywords: ["cybersecurity", "security review", "vulnerability", "IT", "systems"],
    difficulty: "high",
    status: "open"
  },
  {
    id: "opp-015",
    title: "Window replacement in school buildings",
    buyer: "Northern School District",
    source: "Municipal websites",
    category: "Construction",
    type: "municipal-project",
    description: "Replacement of older windows in school buildings, including removal, installation, sealing and waste disposal.",
    deadline: daysFromNow(19),
    publishedDate: daysFromNow(-6),
    location: "North Iceland",
    estimatedValue: 13000000,
    url: "https://example.com/window-015",
    cpvCode: "45421132",
    requirements: ["Construction references", "Waste handling plan", "School safety plan"],
    keywords: ["construction", "windows", "school buildings", "renovation", "installation"],
    difficulty: "medium",
    status: "open"
  },
  {
    id: "opp-016",
    title: "Cleaning contract for healthcare facility",
    buyer: "Regional Healthcare Centre",
    source: "Útboðsvefur",
    category: "Cleaning",
    type: "contract",
    description: "Cleaning services for healthcare facility with strict sanitation and documentation requirements.",
    deadline: daysFromNow(9),
    publishedDate: daysFromNow(-1),
    location: "South Iceland",
    estimatedValue: 17000000,
    url: "https://example.com/health-clean-016",
    cpvCode: "90910000",
    requirements: ["Healthcare cleaning experience", "Sanitation documentation", "Staff training plan"],
    keywords: ["cleaning", "healthcare", "sanitation", "documentation", "daily service"],
    difficulty: "high",
    status: "open"
  },
  {
    id: "opp-017",
    title: "Grant for digital tools in tourism businesses",
    buyer: "Innovation Fund",
    source: "Grant portal",
    category: "IT / Web / Software",
    type: "grant",
    description: "Grant support for tourism SMEs implementing digital booking, customer service or data tools.",
    deadline: daysFromNow(35),
    publishedDate: daysFromNow(-12),
    location: "All Iceland",
    estimatedValue: 4000000,
    url: "https://example.com/grant-017",
    cpvCode: "",
    requirements: ["SME status", "Project description", "Budget plan"],
    keywords: ["grant", "digital tools", "tourism", "booking", "customer service"],
    difficulty: "low",
    status: "open"
  },
  {
    id: "opp-018",
    title: "Road lighting maintenance framework",
    buyer: "Road Administration",
    source: "EU TED",
    category: "Electrical / Infrastructure",
    type: "contract",
    description: "Maintenance framework for road lighting, wiring checks and emergency repairs in selected areas.",
    deadline: daysFromNow(27),
    publishedDate: daysFromNow(-5),
    location: "All Iceland",
    estimatedValue: 30000000,
    url: "https://example.com/road-light-018",
    cpvCode: "50232100",
    requirements: ["Electrical license", "Road safety procedures", "Emergency response"],
    keywords: ["road lighting", "electrical", "maintenance", "wiring", "emergency repairs"],
    difficulty: "high",
    status: "open"
  }
];

function daysFromNow(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}
